"""Regenerate cgm/cgm_log.md — a flat table of every logged CGM reading, by day.

Run after logging new cgm events (peak/nadir/reading) so the table stays current:
    python3 scripts/cgm_table.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from coach_db import connect

OUT = Path(__file__).resolve().parent.parent / "cgm" / "cgm_log.md"


def main():
    conn = connect()
    rows = conn.execute(
        "SELECT day, ts, subtype, value_num, unit, data_json FROM events "
        "WHERE type='cgm' ORDER BY day, ts"
    ).fetchall()
    conn.close()

    by_day = {}
    for day, ts, subtype, value_num, unit, dj in rows:
        by_day.setdefault(day, []).append((ts, subtype, value_num, unit, dj))

    lines = ["# CGM Log — every logged reading, by day", "",
             "Regenerated by `scripts/cgm_table.py` from `db/coach.db` — do not hand-edit, it will be overwritten.", ""]

    for day in sorted(by_day.keys(), reverse=True):
        lines.append(f"## {day}")
        lines.append("")
        lines.append("| Time | Reading | Type | Context | Source |")
        lines.append("|---|---|---|---|---|")
        for ts, subtype, value_num, unit, dj in by_day[day]:
            d = json.loads(dj) if dj else {}
            time = d.get("time", ts[11:16] if len(ts) >= 16 else "")
            val = f"{value_num:.0f} {unit or 'mg/dL'}" if value_num is not None else "—"
            context = d.get("context", "")
            src = d.get("source_image", d.get("source", ""))
            lines.append(f"| {time} | {val} | {subtype} | {context} | {src} |")
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} — {len(rows)} readings across {len(by_day)} days")


if __name__ == "__main__":
    main()
